### ISSUE TITLE
welcome message

### ISSUE THREAD

**Issue by ghost** [dlemstra/line-bot-sdk-dotnet-sample#1]
Hello,

Could you please add a welcome message example to this example where if someone joins the Channel it will say welcome "username"

**Comment by ghost** [comment]
Also would be cool if bot owner can change welcome text within line.
This will be a cool feature showing others how to change stuff based on permission?

**Comment by dlemstra** [comment]
Are you talking about something like special commands that the bot would understands based on permissions? That might be a step to far for this simple example. A join channel message is probably a good idea though.

**Comment by ghost** [comment]
Ya that what I meant but you are correct by saying its a step to far for basic bot but yes on join channel message would be really cool.

Something like this
```
Welcome {username},
Breaking any rule may result in being banned from the chat. (No warning is required) to see rule use !rule command.
```

**Comment by ghost** [comment]
Would it be possible to add such feature?

**Comment by dlemstra** [comment]
Yeah that will be possible, hope I will have time for that this weekend.

**Comment by ghost** [comment]
Great thank you I appreciate it.
